"""
Finite Element Analysis (FEA) module for VOLCO.

This module provides functionality to perform structural analysis on voxel models
generated by VOLCO simulations, including saving and loading analysis results.
"""

from .core import analyze_voxel_matrix, load_fea_results

__all__ = ['analyze_voxel_matrix', 'load_fea_results']